# Generated by Django 3.1.7 on 2021-03-02 16:55

from django.db import migrations

def create_data(apps, schema_editor):
    Manager = apps.get_model('cert_apis', 'Managers')
    Manager(name="Arvind", email="purohith.arvind@gmail.com", phone="00000000", no_of_spot_awards=2).save()

class Migration(migrations.Migration):

    dependencies = [
        ('cert_apis', '0001_initial'),
    ]

    operations = [
	migrations.RunPython(create_data),
    ]
